services:
  webmtr:
    build:
      context: .
      args:
        GUNICORN_WORKERS: ${GUNICORN_WORKERS}
        LISTEN_ADDR: ${LISTEN_ADDR}
        LISTEN_PORT: ${LISTEN_PORT}
    image: webmtr:latest
    container_name: webmtr
    env_file:
      - .env
    ports:
      - "${LISTEN_PORT}:${LISTEN_PORT}"
    cap_drop:
      - ALL
    cap_add:
      - NET_RAW
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    volumes:
      - ./src:/app/src:ro
      - ./logs:/app/logs:rw
